<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="11" failed="1" total="15" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Suite B" duration-ms="504" started-at="2015-03-04T03:09:55Z" finished-at="2015-03-04T03:09:56Z">
    <groups>
    </groups>
    <test name="Test B1" duration-ms="190" started-at="2015-03-04T03:09:55Z" finished-at="2015-03-04T03:09:55Z">
      <class name="com.qtpselenium.framework.suiteB.TestB1">
        <test-method status="SKIP" signature="testB1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteB.TestB1@340f438e]" name="testB1" duration-ms="60" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteB" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Date=24/04/2014, Price=100, Runmode=Y, Iteration=1, Quantity=300, StockName=Tata Motors Ltd., Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestB1 as runmode of suite was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestB1 as runmode of suite was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:106)
	at com.qtpselenium.framework.suiteB.TestB1.testB1(TestB1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB1 -->
        <test-method status="SKIP" signature="testB1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteB.TestB1@340f438e]" name="testB1" duration-ms="40" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteB" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Date=D22, Price=, Runmode=N, Iteration=2, Quantity=D23, StockName=D21, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestB1 as runmode of suite was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestB1 as runmode of suite was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:106)
	at com.qtpselenium.framework.suiteB.TestB1.testB1(TestB1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB1 -->
        <test-method status="SKIP" signature="testB1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteB.TestB1@340f438e]" name="testB1" duration-ms="30" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteB" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Date=D32, Price=, Runmode=N, Iteration=3, Quantity=D33, StockName=D31, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestB1 as runmode of suite was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestB1 as runmode of suite was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:106)
	at com.qtpselenium.framework.suiteB.TestB1.testB1(TestB1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB1 -->
      </class> <!-- com.qtpselenium.framework.suiteB.TestB1 -->
    </test> <!-- Test B1 -->
    <test name="Test B2" duration-ms="178" started-at="2015-03-04T03:09:55Z" finished-at="2015-03-04T03:09:55Z">
      <class name="com.qtpselenium.framework.suiteB.TestB2">
        <test-method status="SKIP" signature="testB2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteB.TestB2@7a0ac6e3]" name="testB2" duration-ms="102" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteB" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col2=X12, Col1=X11, Runmode=Y, Iteration=1}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestB2 as runmode of suite was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestB2 as runmode of suite was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:106)
	at com.qtpselenium.framework.suiteB.TestB2.testB2(TestB2.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB2 -->
        <test-method status="SKIP" signature="testB2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteB.TestB2@7a0ac6e3]" name="testB2" duration-ms="40" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteB" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col2=X22, Col1=X21, Runmode=Y, Iteration=2}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestB2 as runmode of suite was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestB2 as runmode of suite was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:106)
	at com.qtpselenium.framework.suiteB.TestB2.testB2(TestB2.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB2 -->
      </class> <!-- com.qtpselenium.framework.suiteB.TestB2 -->
    </test> <!-- Test B2 -->
    <test name="Test B3" duration-ms="130" started-at="2015-03-04T03:09:55Z" finished-at="2015-03-04T03:09:56Z">
      <class name="com.qtpselenium.framework.suiteB.TestB3">
        <test-method status="SKIP" signature="testB3(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteB.TestB3@96532d6]" name="testB3" duration-ms="60" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteB" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=Z14, Col3=Z13, Col2=Z12, Col1=Z11, Runmode=Y, Iteration=1}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestB3 as runmode of suite was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestB3 as runmode of suite was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:106)
	at com.qtpselenium.framework.suiteB.TestB3.testB3(TestB3.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB3 -->
        <test-method status="SKIP" signature="testB3(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteB.TestB3@96532d6]" name="testB3" duration-ms="40" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteB" finished-at="2015-03-04T08:39:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Col4=Z24, Col3=Z23, Col2=Z22, Col1=Z21, Runmode=Y, Iteration=2}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestB3 as runmode of suite was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestB3 as runmode of suite was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:106)
	at com.qtpselenium.framework.suiteB.TestB3.testB3(TestB3.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB3 -->
      </class> <!-- com.qtpselenium.framework.suiteB.TestB3 -->
    </test> <!-- Test B3 -->
  </suite> <!-- Suite B -->
  <suite name="Suite A" duration-ms="77188" started-at="2015-03-04T03:08:38Z" finished-at="2015-03-04T03:09:55Z">
    <groups>
    </groups>
    <test name="Test A1" duration-ms="76858" started-at="2015-03-04T03:08:38Z" finished-at="2015-03-04T03:09:55Z">
      <class name="com.qtpselenium.framework.suiteA.TestA1">
        <test-method status="PASS" signature="testA1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA1@23223dd8]" name="testA1" duration-ms="32874" started-at="2015-03-04T08:38:38Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Case=CASE_OK, PortFolioName=PortA6, Runmode=Y, Iteration=1, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1 -->
        <test-method status="PASS" signature="testA1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA1@23223dd8]" name="testA1" duration-ms="26102" started-at="2015-03-04T08:39:11Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Case=CASE DUPLICATE_NAME-ERR, PortFolioName=Iter2, Runmode=Y, Iteration=2, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1 -->
        <test-method status="FAIL" signature="testA1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA1@23223dd8]" name="testA1" duration-ms="17083" started-at="2015-03-04T08:39:37Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Case=CASE_OK, PortFolioName=D38, Runmode=Y, Iteration=3, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[FAIL - Not able to Login with Deault Username/password ]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: FAIL - Not able to Login with Deault Username/password 
	at org.testng.Assert.fail(Assert.java:94)
	at com.qtpselenium.framework.util.Keywords.reportFailureAndStop(Keywords.java:277)
	at com.qtpselenium.framework.util.Keywords.loginIfNotLoggedIn(Keywords.java:237)
	at com.qtpselenium.framework.util.Keywords.executeKeywords(Keywords.java:82)
	at com.qtpselenium.framework.suiteA.TestA1.testA1(TestA1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1 -->
        <test-method status="PASS" signature="testA1(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA1@23223dd8]" name="testA1" duration-ms="229" started-at="2015-03-04T08:39:54Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Case=CASE_OK, PortFolioName=xx, Runmode=Y, Iteration=4, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1 -->
      </class> <!-- com.qtpselenium.framework.suiteA.TestA1 -->
    </test> <!-- Test A1 -->
    <test name="Test A2" duration-ms="210" started-at="2015-03-04T03:09:55Z" finished-at="2015-03-04T03:09:55Z">
      <class name="com.qtpselenium.framework.suiteA.TestA2">
        <test-method status="SKIP" signature="testA2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA2@43a25848]" name="testA2" duration-ms="80" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PortFolioName=PortA6, Runmode=Y, Iteration=1, NewPortFolioName=PortA7, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestA2 as runmode of test was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestA2 as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.TestA2.testA2(TestA2.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2 -->
        <test-method status="SKIP" signature="testA2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA2@43a25848]" name="testA2" duration-ms="40" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PortFolioName=Iter2, Runmode=Y, Iteration=2, NewPortFolioName=Iter22, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestA2 as runmode of test was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestA2 as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.TestA2.testA2(TestA2.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2 -->
        <test-method status="SKIP" signature="testA2(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA2@43a25848]" name="testA2" duration-ms="40" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PortFolioName=Iter2, Runmode=N, Iteration=3, NewPortFolioName=Iter22, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestA2 as runmode of test was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestA2 as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.TestA2.testA2(TestA2.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2 -->
      </class> <!-- com.qtpselenium.framework.suiteA.TestA2 -->
    </test> <!-- Test A2 -->
    <test name="Test A3" duration-ms="100" started-at="2015-03-04T03:09:55Z" finished-at="2015-03-04T03:09:55Z">
      <class name="com.qtpselenium.framework.suiteA.TestA3">
        <test-method status="SKIP" signature="testA3(java.util.Hashtable)[pri:0, instance:com.qtpselenium.framework.suiteA.TestA3@34ce8af7]" name="testA3" duration-ms="40" started-at="2015-03-04T08:39:55Z" data-provider="getDataForSuiteA" finished-at="2015-03-04T08:39:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{PortFolioName=PortA7, Runmode=Y, Iteration=1, DependentTests=TestA2-1, Browser=Mozilla}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping the test TestA3 as runmode of test was NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping the test TestA3 as runmode of test was NO
	at com.qtpselenium.framework.util.Utility.validateTestExecution(Utility.java:110)
	at com.qtpselenium.framework.suiteA.TestA3.testA3(TestA3.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1220)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA3 -->
      </class> <!-- com.qtpselenium.framework.suiteA.TestA3 -->
    </test> <!-- Test A3 -->
  </suite> <!-- Suite A -->
  <suite name="My suite" duration-ms="0" started-at="2015-03-04T03:09:56Z" finished-at="2015-03-04T03:09:56Z">
    <groups>
    </groups>
  </suite> <!-- My suite -->
</testng-results>
